name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      - name: Build artifacts
        run: |
          mkdir -p docs/assets/{css,js}
          touch docs/assets/css/style.css
          touch docs/assets/js/{stress,emergency}.js
          
      - name: Deploy
        uses: actions/deploy-pages@v2
