name: Deploy Annihilator

on: 
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Arm Warheads
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs'
          
      - name: Launch
        uses: actions/deploy-pages@v4
